### ISSUE TITLE
Always getting 'Must specify api endpoint' error message

### ISSUE THREAD

**Issue by gkimpson** [cybertk/abao#104]
I have installed the current latest version of abao (0.4.0-beta.4)

When I run the command to initiate the process I always get the error 'Must specify api endpoint' - even when I use the --server flag and add this endpoint the 'must specify api endpoint' error is still appearing?

Can anyone suggest why it would be doing this?

**Comment by plroebuck** [comment]
@gkimpson, please specify **exactly** the command line you tried.

**Comment by plroebuck** [comment]
I suspect you're invoking an older version of **abao**. The error message for current version is **'no API endpoint specified'**

**Comment by gkimpson** [comment]
I ran the command 

    abao myraml.raml

In my raml file the baseUri has a URI set.

**Comment by plroebuck** [comment]
So what when **$ abao --version**?

**Comment by gkimpson** [comment]
The version is 
    0.4.0-beta.4

Should I use a different version?

**Comment by plroebuck** [comment]
No, but I' suspect you have two copies installed, and an older on is on the PATH first...

**Comment by gkimpson** [comment]
I have tried doing npm uninstall abao (both local and global) then re-installing globally.

How do I determine the version installed on the PATH?

**Comment by gkimpson** [comment]
I'll try this 
   npm install -g github:cybertk/abao

**Comment by plroebuck** [comment]
Have any success? The current version is **beta5** which requires the `--server` argument; previous versions do not use that option, and require the API endpoint be specified as cmdline arg instead.

**Comment by cybertk** [comment]
Can we remove `--server` option prefix, just made `${ENDPOINT}` optional. In this way we are compatible with previous versions

**Comment by plroebuck** [comment]
Don't think that's necessary. Cleaner with optional settings processed by `options` code.
Perhaps it should have called it `--endpoint`, but `--server` is more digestable.

**Comment by plroebuck** [comment]
@gkimpson, did you get your installation upgraded and working?
May I close this issue?

**Comment by gkimpson** [comment]
I upgraded & did get it working, please close this issue :)
