### ISSUE TITLE
Response headers are not validated

### ISSUE THREAD

**Issue by samekmichal** [cybertk/abao#124]
Hi, I cannot figure out what I am doing wrong, but the response headers in my setup do not get validated.
```
...
/channels:
  description: Collection of Channels
  get:
    description: Retrieves a list of all channels available.
    responses:
      200:
        headers:
          Content-Encoding:
            required: true
            type: string
            example: gzip
...
```

Or is this something different than what abao README claims?

> Verify that HTTP response headers for each endpoint defined in RAML are supported in service

**Comment by plroebuck** [comment]
Does that RAML include its JSONSchema? That verification (of response headers and body) would happen in hookfile (that **you** would write); **abao** calls your `after` hook function for each path and determines pass/fail based on your assertions.

**Comment by samekmichal** [comment]
Yes, it contains corresponding JSONSchema. So if I understand correctly, the response body gets validated against its JSONSchema "automatically" by abao. But headers have to be validated "manually" in hook files.

**Comment by plroebuck** [comment]
The response code gets done automatically. But the software needs **your** help to validate the response body and headers -- you do so by creating hookfile(s). The just-released **beta.7** version will generate a *Javascript* skeleton hookfile for you. Edit that file, and add your request setup to the `before` hook and response validation (i.e., asserts) to the `after` hook for each route.

**Comment by plroebuck** [comment]
For example, I have a [SIREN](https://github.com/kevinswiber/siren)-based web service.
So for one route, here's a simplified version of one of my hooks:

```javascript
function assertSiren(headers) {
  assert(headers['content-type'] === 'application/vnd.siren+json');
}


// ----------------------------------------------------------------------------
hooks.before('GET /api -> 200', function(test, done) {
  test.request.headers['Accept'] = 'application/vnd.siren+json,*/*;q=0';
  console.log('before-hook-GET-api-200');
  console.log('  ', test.request);
  return done();
});

hooks.after('GET /api -> 200', function(test, done) {
  console.log('after-hook-GET-api-200');
  console.log('  ', test.response);
  assertSiren(test.response.headers);
  assert(test.response.body.class[0] === 'api');
  assert(test.response.body.entitites.class[0] === 'heatmaps');
  return done();
});
```

**Comment by galk-in** [comment]
Planned for implementing
https://github.com/cybertk/abao/issues/137

**Comment by plroebuck** [comment]
If issue remains, leave it open until accepted by person who opened it.

**Comment by samekmichal** [comment]
I can either close the issue or wait until it is implemented in https://github.com/cybertk/abao/issues/137 and close after that. Whatever you prefer.
