### ISSUE TITLE
Add skip to hooks

### ISSUE THREAD

**Issue by galk-in** [cybertk/abao#133]
I have raml. Some of endpoints-responses in API have not implement yet. I want skip this tests.
I tried: 
```javascript
hooks.before('POST /customers -> 201', function (test, done) {
  test.skip = false;
  done();
});
hooks.after('POST /customers -> 201', function (test, done) {
  test.skip = false;
  done();
});
```
It's not work.

**Comment by plroebuck** [comment]
Comment those hooks out and invoke with `--hooks-only` option.

**Comment by galk-in** [comment]
I made pull https://github.com/cybertk/abao/pull/134
After merge we can use:
```js
var hooks = require('hooks');
hooks.skip('DELETE /machines/{machineId} -> 204');
```
@plroebuck @cybertk Please make code review and merge

**Comment by galk-in** [comment]
https://github.com/cybertk/abao/pull/134
