### ISSUE TITLE
Migration to typescript 

### ISSUE THREAD

**Issue by ducin** [cybertk/abao#136]
First of all, thank you for the library.
I know this might sounds strange... but are you opened to migrate abao to typescript?
I find coffee harder to follow because of the different syntax and lack of strong typing. But otherwise abao has great potential and I believe it could rock the stage if it was maintained more... 

Since long time I was thinking of writing such thing myself but I'm convinced it's better to improve something that exists rather than start form scratch. 

I'm very much info supporting abao, but I also strongly believe coffee is the wrong, oh wrong! way to go. I could handle migration. I already did that for 'json-schema-faker'. @cybertk are you opened for it?

**Comment by galk-in** [comment]
https://github.com/cybertk/abao/issues/105
