### ISSUE TITLE
End-to-end testing?

### ISSUE THREAD

**Issue by souravongit** [cybertk/abao#140]
Hi,
   Recently i found this automated api testing tool. I got stuck to call hook method twice. its only working once. Can any one have any idea. Below i mention the scenario.
```javascript
hooks.before('POST /add_category -> 200', function (test, done) { 
  done();
});

hooks.after('POST /add_category -> 200', function (test, done) {
  done();
});

hooks.before('GET /categories -> 200', function (test, done) {
  done();
});
hooks.after('GET /categories -> 200', function (test, done) {
  number_categories = test.response.body.data.categories.length;
  done();
});

hooks.after('DELETE /categories -> 200', function (test, done) {
  done();
});

hooks.before('GET /categories -> 200', function (test, done) {
  done();
});
```
now i again want to category hook for comparing the categories length
i.e. 
```javascript
hooks.before('GET /categories -> 200', function (test, done) {
  done();
});
hooks.after('GET /categories -> 200', function (test, done) {
  rec_number_categories = test.response.body.data.categories.length;
  done();
});
```
some thing like then i can compare "number_categories", "rec_number_categories" these two variables. But second time get method not working.

Thanks.

**Comment by galk-in** [comment]
Hello, @souravongit!
1) In current implementation Abao you can not run same test-case twice.
2) Abao is tool for contact testing. As i see, you try to use abao for end to end testing. I think it's not good idea. In my company we separate contract and end to end testing. You can check difference in this [article](http://martinfowler.com/articles/microservice-testing/#testing-contract-introduction)
3) If you can make your checks without running same test-suit twice, then use afterAll hook. Code example:
```javascript
hooks.afterAll(function(done) {
    //make some checks
    done();
});
```

**Comment by souravongit** [comment]
Thanks @galk-in. Is there a good way of end to end testing you suggest.

Thanks.

**Comment by plroebuck** [comment]
@galk-in, please **stop** closing issues immediately. You didn't even answer his question before doing so.

**Comment by galk-in** [comment]
@plroebuck Okey

**Comment by plroebuck** [comment]
@souravongit, as a workaround for only being able to call the API endpoint once, you can put the hooks needed to be called a second time into a different hooksfile. Then invoke like this:

```bash
$ abao api.raml --hookfiles="test_alt_machines_hooks.js" --hooks-only
```

Also suggest using `assert()` in your after-hook to determine if test is functioning as expected.
Don't know what you were trying to do, but maybe something like this...

```javascript
expected = {
  ncategories: 5;
};

hooks.before('GET /categories -> 200', function (test, done) {
  test.request.ncategories = expected.ncategories;  // or whatever your param to do so
  done();
});

hooks.after('GET /categories -> 200', function (test, done) {
  assert(test.response.body.data.categories.length === expected.ncategories);
  done();
});
```

Does that help?

**Comment by souravongit** [comment]
@plroebuck Thanks for responded.
So what i want to do i.e. say i have four methods add,edit,list,delete categories.
So in hook file 1st i mention the add method & at the same time i store the resppnse in a global variable. So   on after that i have list method from there i just keep the count of the categories by list method response then delete method mention so after delete i want to call the list method againg and compare the categories count with stored global variable count by assert.
Mainly store total category count to global variable to then after delete recall & compare.
Please help me if there is any way.also if you have any queries then feel free to ask me.

Thanks.

**Comment by plroebuck** [comment]
End-to-end testing is difficult to do with **Abao**. I would:

1. Call list function (GET) first to get count and store response count to disk.
2. Call add function (POST) and verify response code is 200 or 201. [second hookfile]
3. Load previous result (step1) from disk. Call list function (GET) again and assert response count equal to previous result. Save result to disk again. [third hookfile]
4. Call delete function (DELETE) and verify response is 200. [fourth hookfile]
5. Load previous result (step3) from disk. Call list function (GET) third time and
    assert (response count+1) equal to previous result [fifth hookfile]

**Abao** isn't really meant for this style testing (as you can see), but it is possible...

HTH

**Comment by souravongit** [comment]
I already tried that but the storing value to disk not done yet.it throws some javascript error like File undefined. Can you please suggest me the approch to store data on disk. Just a small example to store data & get data to next hookfile a simple one.

Thanks for your earlier suggesstion.

**Comment by plroebuck** [comment]
**Completely untested code follows.**

I slightly modified your calls above to more closely match a canonical REST-like API, specifically:
* Each call has same-named endpoint for its base (`/add_category` is **NOT** RESTful)
* POST passes new category in request body (and uses same-named endpoint 
* DELETE has query parameter to specify category to delete by its name

Consists of a utility file and five different hookfiles as described above.

`test_util.js`
```javascript
module.exports = (function () {
  'use strict';

  var
    fs = require('fs'),
    path = require('path'),
    process = require('process');

  var
    tmpdirname = path.join(process.env.TMPDIR, 'abao'),
    pathname = path.join(tmpdirname, 'test_category.txt');

  fs.existsSync(tmpdirname) || fs.mkdirSync(tmpdirname);

  return {
    sampleCategoryName: 'awesome',
    fetchCategories: function () {
      return JSON.parse(fs.readFileSync(pathname));
    },
    storeCategories: function (categories) {
      fs.writeFileSync(pathname, JSON.stringify(categories));
    }
  };
})();
```

`test_categories_step1_hook.js`
```javascript
var
  util = require('test_util'),
  hooks = require('hooks');

hooks.after('GET /categories -> 200', function (test, done) {
  console.log('step1 - GET (after)');
  util.storeCategories(test.response.body.data.categories);
  done();
});
```

`test_categories_step2_hook.js`
```javascript
var
  hooks = require('hooks');

hooks.before('POST /category -> 200', function (test, done) {
  console.log('step2 - POST (before)');
  test.request.body = { category: newcat }; 
  done();
});

hooks.after('POST /category -> 200', function (test, done) {
  console.log('step2 - POST (after)');
  done();
});
```

`test_categories_step3_hook.js`
```javascript
var
  util = require('test_util'),
  hooks = require('hooks'),
  assert = require('chai').assert;

hooks.after('GET /categories -> 200', function (test, done) {
  var
    categories = util.fetchCategories();

  console.log('step3 - GET (after)');
  assert(test.response.body.data.categories.indexOf(util.sampleCategoryName) > -1);
  assert((categories.length+1) === test.response.body.data.categories.length);
  done();
});
```

`test_categories_step4_hook.js`
```javascript
var
  util = require('test_util'),
  hooks = require('hooks');

hooks.before('DELETE /categories/{category} -> 200', function (test, done) {
  test.request.params.category = util.sampleCategoryName;
  console.log('step4 - DELETE (before)');
  done();
});

hooks.after('DELETE /categories/{category} -> 200', function (test, done) {
  console.log('step4 - DELETE (after)');
  done();
});
```

`test_categories_step5_hook.js`
```javascript
var
  util = require('test_util'),
  hooks = require('hooks'),
  assert = require('chai').assert;

hooks.after('GET /categories -> 200', function (test, done) {
  var
    categories = util.fetchCategories();

  console.log('step5 - GET (after)');
  assert(test.response.body.data.categories.indexOf(util.sampleCategoryName) === -1);
  assert(categories.length === test.response.body.data.categories.length);
  assert(categories.sort().join('|') === test.response.body.data.categories.sort().join('|'));
  done();
});
```

**Comment by plroebuck** [comment]
@souravongit, did the example unit test work for you?

**Comment by plroebuck** [comment]
@souravongit, does the example script address your problem? Can we close this issue?

**Comment by souravongit** [comment]
Yes I  implement your thing with some small changes & it works .Thanks Once again.
But now i think also that this not the actual way for End-to-end testing. Can you please suggest me any End-to-end testing process. My code base is in ruby on rails.

Thanks.

**Comment by galk-in** [comment]
@souravongit did you see [cucumber](https://github.com/cucumber)? My team use gherkin language for end2end tests. Maybe it will help you.

**Comment by souravongit** [comment]
Ok i will go through with this.Thanks.

**Comment by plroebuck** [comment]
Personally, I'd try writing mine with Mocha (same as **Abao** uses underneath). Good luck!
