### ISSUE TITLE
hooks.after returns response body null

### ISSUE THREAD

**Issue by kol9n93** [cybertk/abao#144]
Good day. I have an issue:
hooks.after returns request.body null, but should return json object.
I can see in server console that response body is correct, but hooks.after shows null response.body.

**Comment by plroebuck** [comment]
We'd need a little more than that to troubleshoot your problem. Have a minimal RAML, hooksfile, and public-facing server? Otherwise, load your result and corresponding schema [online](http://www.jsonschemavalidator.net/) and see if they match.

**Comment by kol9n93** [comment]
For example
`/{id}:
  uriParameters:
    id:
      example: /api/suppliers/adminSupplier/bankAccounts/64
      type: number
      description: Bank Account id

  put:
    description: Update existing bank account
    body:
      application/json:
        example: |
          {
            "bankName": "new bank"
          }
    responses:
      200:
        body:
          application/json:
            example: |
              {
                "id": 64
                "ownerObjectType": "com.jcatalog.supplier.SIMSupplier"
                "ownerObjectId": "adminSupplier"
                "bankCode": null
                "bankName": "new bank"
                "bankBranchCode": null
                "countryId": "DZ"
                "city": "test"
                "iban": "test"
                "swiftCode": "test"
                "type": "test"
                "accountNo": null
                "currencyId": "EUR"
                "createdOn": "2016-05-02T10:38:33.000Z"
                "createdBy": "admin@gmail.com"
                "changedOn": "2016-05-02T10:53:49.000Z"
                "changedBy": "admin@gmail.com"
              }
      404:
        body:
          application/json:
            example: |
              {
                "message": "Not Found"
                "errors": [0]
              }`
it is from my RAML doc.

And there is my hook for that RAML:
`hooks.before('PUT /suppliers/{supplierId}/bankAccounts/{id} -> 200', function(test, done) {
  test.request.headers['Content-Type'] = 'application/json';
  test.request.params = {
    supplierId: supplierId,
    id: bankAccountId
  };
  test.request.body = {
    ownerObjectId: supplierId,
    bankName: "my new bank",
    iban: "123456789",
    swiftCode: "12345",
    createdBy: adminUser,
    changedBy: adminUser
  };
  return done();
});

hooks.after('PUT /suppliers/{supplierId}/bankAccounts/{id} -> 200', function(test, done) {
  let bankAccount = test.response.body;
  assert.match("my new bank", bankAccount.bankName);
  done();
});`

In hooks.after response.body is null.

**Comment by plroebuck** [comment]
What is the response (including headers) from your server if you send the same parameters using `curl`?

**Comment by plroebuck** [comment]
Include relevant entries from the server log. Of course, scrub internal IP addrs and/or hostnames with semantic names (i.e., replace server hostname with `server`, proxy hostname with `proxy`, and your machine with `client`).

**Comment by plroebuck** [comment]
Oh, wait a minute. Your RAML does not include the appropriate JSONschema for the response. This is **required** to get the response body for evaluation.

**Comment by plroebuck** [comment]
For example, this is what I use for my error responses.

```json
{
  "$schema": "http://json-schema.org/draft-04/schema",
  "type": "object",
  "required": true,
  "properties": {
    "code": {
      "type": "string",
      "required": true
    },
    "message": {
      "type": "string",
      "required": true
    }
  }
}
```

Put yours in an external file `error.json` in your schema directory.
Edit your RAML to specify and use the schema:
```raml
schemas:
  - error: !include schemas/error.json


...
      406:
        body:
          application/json:
            schema: error
```

Invoke **Abao** with `--schemas` option to specify the directory where you put them (example above has them in the appropriately named "schemas" subdirectory).

**Comment by plroebuck** [comment]
Did this explanation somewhat resolve your issue?

**Comment by kol9n93** [comment]
Yes, sure, thank you

**Comment by galk-in** [comment]
@kol9n93, @plroebuck can we close this issue?

**Comment by kol9n93** [comment]
Yes, sure.
