### ISSUE TITLE
Still on v0.4.0-beta.8 in npm-reg

### ISSUE THREAD

**Issue by oleics** [cybertk/abao#179]
https://www.npmjs.com/package/abao
says v0.4.0-beta.8, so `npm install abao` will install that version, not v0.4.0-beta.10
I suggest updating via npm. Thank you :)

**Comment by oleics** [comment]
Related but closed issue: #104

**Comment by plroebuck** [comment]
Well, it's not as hopelessly out-of-date as the RunKit version (0.3.1)...
Sorry, but I have no idea how either website determines what our current version;
it's definitely broken though.

**Comment by oleics** [comment]
The maintainer (quanlong) can publish the latest version via `npm publish`.
cc @cybertk ;)

**Comment by galk-in** [comment]
Hello, guys.
We have auto-deploy to npm on every tag. Check the .travis.yml file
As I see tag [build v0.4.0-beta.9](https://travis-ci.org/cybertk/abao/builds/136155015) was broken.
So travis didn't publish v0.4.0-beta.9 version.
One month ago cybertk added draft for v0.4.0. Just now I made release. So we have v0.4.0 at npm.

Do we need disscuse some details about this issue? Can we close this issue?

**Comment by oleics** [comment]
@galk-in 
All fine, v0.4.0 installs now via `npm`.
Thank you :)

**Comment by oleics** [comment]
Though, does not resolve #104

**Comment by plroebuck** [comment]
Don't believe this has anything to do with #104.

**Comment by plroebuck** [comment]
I updated the version to 0.4.1 and verified that NPM has that version available.
I remember someone recently doing a merge to main with a version# that had already been released; depending on how/when that was corrected, it could explain the version mismatch (i.e., the one NPM had was actually a newer version than it purported).
