### ISSUE TITLE
`baseUri` defined, but getting "no API endpoint specified"

### ISSUE THREAD

**Issue by oleics** [cybertk/abao#180]
I'm using abao via `npm`. NPM-Version is: abao@0.4.0

Related issue: #104 

My thought on this: Make `--server` required and implement `--use-default-server` flag later on. My reason for putting this behind a flag is, that it makes hammering production-servers with requests harder. And maybe don't use the default server at all and always require the server to be specified.

jm2c and cheers!

**Comment by galk-in** [comment]
@oleics, about your request --use-default-server my answer is 'No', because we don't need extra flags. It's extra code and work. Please, check [0.4.1-beta.0](https://www.npmjs.com/package/abao) version. The bug was fixed.

If all is okey, then can we close the issue?

**Comment by oleics** [comment]
@galk-in My fault, if I was not concrete enough. I'm very aware that a flag means extra code/work/lines to maintain. This (and running calls against production-servers by-default) would be enough reasons for me to completely drop the feature of using baseUri as the default server ;) But it's not up to me to decide here :)

And sure, the bug is fixed, so close this issue.

**Comment by plroebuck** [comment]
@oleics, why is this an issue at all? It is **designed** to run against the RAML-designated server by default. If you want to run against a staging server, use the ``--server`` cmd-line argument. If you're doing new development, either add the designated API endpoint to your ``/etc/hosts`` file and impersonate the production server, or change the ``baseUri` property in your RAML file to access your development server.
