### ISSUE TITLE
Documentation is not clear

### ISSUE THREAD

**Issue by cybertk** [cybertk/abao#19]
Issue reported by Abe via email.

I am looking at the documentation for abao, and I wonder if you have time to add a little bit more information. Maybe a few examples?

I ask because when abao validates the request body or the response body, it's not clear what 'validating the JSON schema' really means. It would be great to see an example that shows, okay, abao obtains a request body like this ... abao validates a response body like this ...

Also I notice that the Mocha link in the README is broken.

If you write something up, I would be happy to edit it. So you can write it up in rough form, and I will polish it for you.

**Comment by chuckledog** [comment]
I'm new to RAML but finding api-driven development very satisfying so far.  Abao and ramlev are great, thanks for publishing these.

Thought I'd share a newbie lesson learned -- it seems like my first forays were missing uriParameters sections which was causing "undefined" ids, see http://stackoverflow.com/questions/25998115/describing-uri-parameters-in-raml

So I was seeing  "GET /api/machines/undefined HTTP/1.1" 400 in my server logs when using abao.  After adding the uriParameters section I started seeing "GET /api/machines/1 HTTP/1.1" 400.
