### ISSUE TITLE
Expose test.request in beforeAll hook

### ISSUE THREAD

**Issue by laurentperez** [cybertk/abao#20]
Hi

It would be nice to expose at least test.request instead of just "done" under beforeAll

Use case : setting test.request header of Authorization for all requests instead of repeating it.

thanks

**Comment by honzatrtik** [comment]
This would be really usefull. Accessing test.request in beforeAll and test.response in afterAll allows among other things for better logging etc...

**Comment by jekhardt** [comment]
This would also be helpful for #34 to be able to set default headers programmatically in beforeAll to eliminate extra steps before running abao or repetitively updating test.request in each before hook for authorization headers.

**Comment by coltonlw** [comment]
--header adds a header, but for people who need to add a query or body parameter to every request, there is currently no good way to do so.

+1

**Comment by coltonlw** [comment]
After seeing the PR that was merged, I tried beforeEach with a signature of (test, done) and that worked great.  Suggest adding to README

**Comment by cybertk** [comment]
@coltonlw Could you please help on it? Add your case into README.
