### ISSUE TITLE
Ability to override endpoints ordering

### ISSUE THREAD

**Issue by laurentperez** [cybertk/abao#22]
Currently the parser produces a list of endpoints given the raml.

For example the POST and DELETE are listed before the GET. When I need a scenario like : post first, then get, then delete, it fails because get will be called after delete, because it follows the endpoints order. For this to work I have to split my scenario in multiple files, and call them in the right order. Not very handy.

If we could alter the order with a custom endpoints order it would solve it :) It would allow me to write an ordering specifically for my use case.

**Comment by nexus49** [comment]
+1 this would be really helpful for us as well.

**Comment by joostmeijles** [comment]
I would like more fine grained control on test ordering as well, e.g. for testing two calls to the same endpoint and where each call has a different response code.

**Comment by misfitdavidl** [comment]
yes, it should be more powerful for abao
