### ISSUE TITLE
abao fails to send URI parameter 

### ISSUE THREAD

**Issue by scordatura** [cybertk/abao#23]
My RAML has a GET against a resource with one URI parameter:

```
/my_resource:
  /{param}:
    description: |
      TBD.
    type:
      collection-item:
        exampleItem: !include my_resource-get-item.sample
```

The parameter is in the **.sample** file with an integer value:

```
{
    "param": 1033
}
```

When I run abao, it seems that abao is failing to send that parameter with its integer value. My API obviously thinks it's undefined:

```
  1) GET /my_resource/{param} -> 200 Validate response code and body:
     Uncaught AssertionError: Got unexpected response code:
{"errors":"Record not found: Couldn't find MyResource with param=undefined"}
Error: expected 404 to equal '200'
    at Test.assertResponse (/usr/local/lib/node_modules/abao/lib/test.js:88:14)
    at /usr/local/lib/node_modules/abao/lib/test.js:3:61
    at /usr/local/lib/node_modules/abao/lib/test.js:70:11
    at fn (/usr/local/lib/node_modules/abao/node_modules/async/lib/async.js:641:34)
    at Object._onImmediate (/usr/local/lib/node_modules/abao/node_modules/async/lib/async.js:557:34)
    at processImmediate [as _immediateCallback] (timers.js:345:15)
```

The API docs in Anypoint work fine. Sending the same request at the command line with curl works fine too. 

Either I am using abao incorrectly, or this is a bug.

**Comment by smt-pi** [comment]
I am trying to get some endpoint tests to be skipped - adding 'test.skip = true' does not seem to work, and other than @skip being initialised to false in the constructor of Test, I cannot see any reference to it.

Not sure if I misunderstand how to skip a test, or if this is a bug.

Any guidance would be appreciated.

Thanks.

**Comment by cybertk** [comment]
Could you share your hooks?

**Comment by smt-pi** [comment]
An example of one of the hooks is as follows:

    before 'DELETE /node/{node_id} -> 200', (test, done) ->
      test.skip = true
      done()

**Comment by sprakasam** [comment]
test.skip = true doesn't work
