### ISSUE TITLE
Question about usage

### ISSUE THREAD

**Issue by sielay** [cybertk/abao#26]
Hi

I am not sure, if I understand how you want people to use abao. I have specific use case and could you please tell me, if your concept suits that (or may suit after improvements).

I assume test for RAML should:
 * compose request basing on RAML definition file (I can't figure out how to make query params, also example values being used in test)
 * validate response basing on RAML definition file (json schema validation should be used, if defined, seems not working)
 * use predefined/mocked combinations of params

If we go out of RAML (I don't see that in RAML itself) testing great would be to test specific query to expect specific data returned.

Anyhow. Could you tell me, if abao is meant to cover that scenario and (regards issues in brackets) how we can address them?

**Comment by cybertk** [comment]
Yeah, it covers your use case. I'm considering provide some examples.

**Comment by sielay** [comment]
That would be awesome :+1: :)

**Comment by sielay** [comment]
@cybertk I want to present to corpo choice between RAML and Swagger. Your tool seems to be deal maker here ;) If we can provide examples of working full test, that would be far enough. Anyhow I have 1,5 week to prepare.

**Comment by scordatura** [comment]
@Lukasz: I could demo my working examples if you want to meet on Skype.
@cybertk: Would that be okay with you?

Abraham Raher | *Apps Team Technical Writer*

**Comment by cybertk** [comment]
Sounds good for me

Sent from Outlook




On Mon, Mar 2, 2015 at 10:21 AM -0800, "Abraham Raher" <notifications@github.com> wrote:










@Lukasz: I could demo my working examples if you want to meet on Skype.

@cybertk: Would that be okay with you?



Abraham Raher | *Apps Team Technical Writer*





On Mon, Mar 2, 2015 at 3:48 AM, Łukasz Marek Sielski <

**Comment by scordatura** [comment]
I have sent Łukasz a Skype contact request. @Łukasz, feel free to contact
me through Skype if a demo from me would help.

Abraham Raher | *Apps Team Technical Writer*

**Comment by lukasz** [comment]
I think you've got wrong Łukasz's e-mail :)
3 mar 2015 00:56 "Abraham Raher" <notifications@github.com> napisał(a):

> I have sent Łukasz a Skype contact request. @Łukasz, feel free to contact
> me through Skype if a demo from me would help.
>
> Abraham Raher | *Apps Team Technical Writer*
>
>

**Comment by sielay** [comment]
Lolz lukaszsielski@gmail.com. Will see, if I can get on skype in sensible hours. But not only for my sake, but for all it would be best to improve documentation. I start now to understand that hooks are part of that functionality. Maybe it's odd comment @cybertk but making all just in CoffeeScript limits very much audience. For me this language is unreadable mutation of JavaScript. Many people won't pick up project just because of that. It's worth investigating JS based hooks.

**Comment by cybertk** [comment]
Hooks can be wrote in javascript, like [this](https://github.com/cybertk/abao/blob/master/test/fixtures/test2_hooks.js)

**Comment by lukasz** [comment]
Guys. seriously - stop emailing me, please... :) I have nothing to do with
that project... Not even a front-end developer :)

**Comment by cybertk** [comment]
@lukasz You need unsubscribe this topic on right panel.

**Comment by cybertk** [comment]
@sielay I added javascript examples of hookfile in **README**

**Comment by sielay** [comment]
@cybertk lovely ; @scordatura  thanks for email. At the moment can't skype from corpo and can't figure out time to do some conf, but will keep contact in case guys will say `go` with using this tool

**Comment by sielay** [comment]
@cybertk one thing I don't understand. I have such RAML
```
/reviews/search.json:
  get:
      queryParameters:
        q:
          description: Query
          example: iphone
        query:
          example: iphone
        limit:
        Brand:
          example: Apple
        Category:
          example: phone
      responses:
              200:
                body:
                  application/json:
                    schema: !include search.schema.json
```

`search.schema.json` is JSON schema file. Do you somehow validate JSON Schema against response. Or should I do that inside hook. If inside hook, then do you expose loaded response definition into the hook?

**Comment by cybertk** [comment]
**Abao** will validate real response against JSON Schema defined in RAML automatically unless you did not specify schema in RAML. Hooks are used to do other customized works, such as define queryParameters, validate responses over JSON layer, i.e. response **ID** equals some value.

**Comment by cybertk** [comment]
In some case, you will get **Abao** up to validate all responses without hooks, if your API is simple and all related info can be read from RAML.

**Comment by sielay** [comment]
Ok, will test. My issue in given example is that, when I added non existing required field to schema nothing popped out. But I might do something wrong.

**Comment by cybertk** [comment]
You can try to change existing field's data type, jsonschema allow non-existing field unless you specified with `additionalProperties: false`

**Comment by cybertk** [comment]
Is you problem solved?

**Comment by sielay** [comment]
Oh. Yes. Solved. Abao proven that RAML is best choice for us so far.

**Comment by sichvoge** [comment]
@sielay sounds good! ;)
