### ISSUE TITLE
Maintaining Session State throughout the test

### ISSUE THREAD

**Issue by agrover8** [cybertk/abao#34]
Maintaining Session State throughout the test

Is there any way in ABAO we can maintain the http session for all the test cases present in the hook file?

I have 100 endpoints, but it works only if first authentication endpoints run and rest of the endpoints works in the same session only.

**Comment by cybertk** [comment]
Yes. 

Assume your session is implemented with OAuth Token, you can authenticate user in `beforeAll` hook and save Token there, then in next endpoint test hook, assign the Token to `request.header` or `request.querystring`

If you session is passed by HTTP Header, you can also specify the Session with `-h` option of **Abao**, i.e. 

```
$ abao api.raml http://example.com -h "Authorization: Basic AABBCCDDEE"
```
