### ISSUE TITLE
Schema required to get response body hook `after`

### ISSUE THREAD

**Issue by sielay** [cybertk/abao#40]
At least please add to doc, that you won't get body, if there is no schema in RAML ;) Debugging it took a while ;0

**Comment by ferrylauda** [comment]
+1

**Comment by plroebuck** [comment]
This would seem partially done, but is now misleading the opposite way...

From the README.md:
```
Abao validates the response from server against jsonschema defines in RAML, so there must be schema section in defined in RAML.
```

It **does** allow you to run each test without any schema, though only the status code can be verified.
