### ISSUE TITLE
Can't locally install abao

### ISSUE THREAD

**Issue by dlinnemeyer** [cybertk/abao#41]
We tried adding abao to our package.json and running npm install from our project root, but we got the failure mentioned in #9. I noticed the readme requires npm install -g. Is there no way to install abao as a local project dependency?

I'm not normally a node developer; is this common practice? Just wondering.

Other than this, abao has been working great. Thanks.

**Comment by cybertk** [comment]
Could you try to install **grunt** first with `npm install grunt-cli`

**Comment by dlinnemeyer** [comment]
Yeah I tried that. I believe I had to use sudo and I tried both with and without the -g.

**Comment by cybertk** [comment]
Could you post your errors here?

**Comment by dlinnemeyer** [comment]
Nevermind. Looks like it was a problem in our package.json file. Once I got that straightened out, it installed fine locally. Sorry about that.
