### ISSUE TITLE
response bodies are not verified against JSON schemas

### ISSUE THREAD

**Issue by bpytlik** [cybertk/abao#42]
At this [line] (https://github.com/cybertk/abao/blob/74996977fdf5c837c0f39af18e42b426b0ff6189/src/test.coffee#L71) we see `schema` be set to `@response.schema`. `schema` is then passed to assert.jsonSchema. From [here](https://github.com/Bartvds/chai-json-schema/#jsonschemavalue-schema) we see that the schema passed should be an object.

At [this line in add-tests.coffee](https://github.com/cybertk/abao/blob/74996977fdf5c837c0f39af18e42b426b0ff6189/src/add-tests.coffee#L81) however, we see that test.response.schema is a list.

If you give `assert.jsonSchema` a list instead of an object, then it will not throw an exception even when the object doesn't match the schema. Here's an example:
```
coffee> a = {foo: 3}
{ foo: 3 }
coffee> schema = {type: "object", required:["skin"], properties:{skin:{type:"string"}}}
{ type: 'object',
  required: [ 'skin' ],
  properties: { skin: { type: 'string' } } }
coffee> chai.assert.jsonSchema(a, schema)
AssertionError: expected value to match json-schema '{"type":"object","required":["...' -> '{"foo":3}'
      Missing required property: skin
          schema: {"type":"object","required":["skin"],"properties":{"skin":{"...
          rule:   /required/0 -> "skin"
  at Function.assert.jsonSchema (/aux0/brock/pub-api/dev_deps/node_modules/chai2-json-schema/index.js:176:40)
...
coffee> chai.assert.jsonSchema(a, [schema])
undefined
```

If you look at the test cases for [test.coffee](https://github.com/cybertk/abao/blob/74996977fdf5c837c0f39af18e42b426b0ff6189/test/unit/test-test.coffee#L185), you see that test.response.schema is expected to be an object.

**Comment by cybertk** [comment]
You can have a look at PR #30, I did not find a general/consistent solution yet. What's your advice?

**Comment by bpytlik** [comment]
I'm not sure what's trying to be achieved by storing more than one schema in the test.response.schema. chai-json-schema expects that to be the schema to be validated against.

Since I'm not sure what that pull request was trying to achieve, it's hard for me to say what the right solution should be. Based on the RAML spec and [the discussion](http://forums.raml.org/t/how-do-i-reference-nested-sub-schemas-from-raml/583/6) around it, the expectation is that references have been resolved before RAML sees them.

I suppose you could try to resolve the references within and between the schemas when you load them, but I don't think that's actually necessary.

I'll send a PR shortly that, while not solving the issue that PR 30 tried to solve, at least means that the response will once more be checked against the schema.

**Comment by cybertk** [comment]
We implement [csonschema][] to achieve **resolved all references in jsonschema before RAML sees them**. You can also have a look on that.

PR #30 is aslo a solution to achieve that goal. It simply stored all parsed nested references into `test.response.schema`.

So at this moment, I think we have two different solutions to parse nested references:

1. Replace nested schema reference with parsed schema inside context.
1. Leave nested schema reference unchanged and put parsed schema in another structure.

[csonschema]: https://github.com/cybertk/csonschema

**Comment by bpytlik** [comment]
I agree that PR#30 stored all the parsed schemas in a structure. It did not resolve any of the references internally. If you don't like my PR, then I'd suggest trying to use one of the existing libraries to expand the references. I didn't find any that solved my needs, but maybe you'll have better luck.

This bug means that abao is actively misleading users of abao with JSON schemas since they think they're verifying the contents of their responses against the schema(s) they've provided and that's not actually happening. I would suggest taking either my PR, or some other similar change, as soon as possible.

**Comment by bpytlik** [comment]
Closing as the PR#43 was merged.
