### ISSUE TITLE
support Oauth2 security scheme

### ISSUE THREAD

**Issue by seebi** [cybertk/abao#53]
maybe I miss something but APIs are often secured by OAuth2 or other schemes but ABAO does not support that

**Comment by cybertk** [comment]
OAuth2 authentication is actually carry a token with HTTP Request.

Although **abao** dose not support OAuth explictly, you can use `-h` option as a workaround, such as

```
$ abao api.raml http://example.com -h "Authorization: Bearer AABBCCDDEE"
```

**Comment by seebi** [comment]
Thanks for that. Can I also add additional URI parameter? OAuth2 supports both request params and URI params (`access_token`)

**Comment by cybertk** [comment]
Yes, you can use hooks for that.
