### ISSUE TITLE
test.response.header is null, tough it is specified in RAML

### ISSUE THREAD

**Issue by zavalit** [cybertk/abao#58]
Hi, first of all, guys, really awesome tool, bring our QA to a new level.

the Problem that we experience is the following:
for the Raml spec:
```
/users:
  description: Entrypoint to handle users
  post:
    description: Create a user
    body: 
      application/json:
        schema: user
    responses:
       201:
        description: A user was created
        headers:
          location:
            description: "Relative URL of the created user."
            type: string
            required: true
            example: /users/123456
        body: null
```

the **test** object that abao creates for that looks like that:
```
{ assertResponse: [Function],
  name: 'POST /users -> 201',
  skip: false,
  request:
   { server: 'http://localhost',
     path: '/users',
     method: 'POST',
     params: {},
     query: {},
     headers: { 'Content-Type': 'application/json' },
     body: {} },
  response: { status: '201', schema: null, headers: null, body: null } }
```

as you can see, **response.headers** is equal to null

```
abao --version
0.4.0-beta.2
```
thank's a lot for your help.

**Comment by cybertk** [comment]
We have [tests](https://github.com/cybertk/abao/blob/1f3e6510cb8c36f025ec5fe859ce33e60b8b1695/test/unit/test-runner-test.coffee#L355-L386) to cover the function of **Parsing headers**. Is there any difference between the test scenario and your?

**Comment by cybertk** [comment]
I saw the tests only cover parsing headers of request. I think **abao** may not support parsing response headers yet.

**Comment by plroebuck** [comment]
@cybertk, maybe I'm not understanding you, but this would seem an easy one-line fix in
[test.coffee](https://github.com/cybertk/abao/blob/master/lib/test.coffee#L79-L84).

On L82 (after asserting the response is not null), add this line:
```coffeescript
@response.headers = response.headers
```

**Comment by cybertk** [comment]
@plroebuck  You are right.

**Comment by plroebuck** [comment]
@zavalit, note that my commit will **only** provide the response headers to after hooks.
As far as the header specified in your RAML, you will need to verify its existence in
your after test hook; it will **not** be verified automatically.
