### ISSUE TITLE
Clear Cookies

### ISSUE THREAD

**Issue by agrover8** [cybertk/abao#64]
Hi,

Is there any way in Abao we can clear cookies before making request?

**Comment by plroebuck** [comment]
I would expect them to be passed (abao-wise) as ```test.req.cookies``` -- perhaps [cookie-parser](https://www.npmjs.com/package/cookie-parser) as a potential prerequisite candidate? Are you requesting session support?

**Comment by plroebuck** [comment]
Couldn't you just use `Set-Cookie` header in `before` hook to do this yourself?

**Comment by plroebuck** [comment]
Is this issue still unresolved?

**Comment by aisensiy** [comment]
@plroebuck It is possible to send a separate require in before hook and after hook? I think I need some kind of session support and I need to test the raml to get different status code for different sessions.
