### ISSUE TITLE
error with test

### ISSUE THREAD

**Issue by atdiff** [cybertk/abao#66]
I've setup hook files replicating the 3 examples in the [readme](https://github.com/cybertk/abao#example):

- before_hook.coffee - with before and after
- callback_hook.coffee - one with beforeAll and afterAll
- test_hook.coffee - one with test

When I run the abao command
`abao http://localhost:8081/raml http://localhost:8081/ --hookfiles=*_hook.*`

I get the following error:

> Error reading hook files (before_hook.coffee,callback_hook.coffee,test_hook.coffee)
> This probably means one or more of your hookfiles is invalid.
> Message: undefined is not a function
> Stack: TypeError: undefined is not a function
>   at Object.<anonymous> (C:\dev\test_hook.coffee:3:1)
>   at Object.<anonymous> (C:\dev\test_hook.coffee:1:1)

Am I missing something?  I want to be able to validate the request parameters and response contents.
I also tried running "npm test" in the command line of that folder and received a grunt error.  Is a grunt file required to run the tests?

**Comment by plroebuck** [comment]
Dunno, but maybe try renaming your files so that the one with beforeAll/afterAll comes first alphabetically. I wrote mine in JS, with "init_hooks.js" having empty beforeAll/afterAll, and each route having its file named "test_<route>_hooks.js" with before/after functions. Not sure what you have in "test_hook.coffee" -- the test is the before/after combination, setting up request and asserting against the response. Leave Grunt out of this until you can get the cmdline to work.

**Comment by atdiff** [comment]
My test_hook.coffee file has this code from the examples
`{test} = require 'hooks'

test 'GET /machines -> 200', (response, body, done) ->
    assert.deepEqual(JSON.parse(body), ["machine1", "machine2"])
    assert.equal(headers["content-type"], 'application/json; charset=utf-8')
    return done()`

**Comment by atdiff** [comment]
Are hooks required to validate the structure of the content in the response?  Or do the hooks only validate that the content matches the expected content?  Is it structure/schema or actual data?

**Comment by plroebuck** [comment]
Hooks are just functions called pre/post. Typical usage would be to set your input params in the 'pre' hook, then assert against the response in the 'post' hook. Hook function signature should be 'function(test, done)' where 'test' object contains both 'request' and 'response' objects. So your 'test_hook.coffee' above makes no sense. I'm new to this project (and don't know coffee), but I would sort of translate your route as:

```coffee
{before, after} = require 'hooks'

after 'GET /machines -> 200', (test, done) ->
  console.log 'response:' test.reponse
  assert(test.response.status === 200)
  assert.deepEqual(JSON.parse(test.response.body), ["machine1", "machine2"])
  assert.equal(test.response.headers["content-type"], 'application/json; charset=utf-8')
  done()
```

Based on other issues, not sure whether response header parsing works. Based on my experience, response body itself is sometimes 'null'. **If you haven't defined a schema for the response in your RAML, all you can verify is the response code.**

It would be an great addition if @cybertk would include a couple commented "best practice" examples of how to do various test activities.

HTH

**Comment by atdiff** [comment]
Thanks for the info @plroebuck.  Unfortunately no luck with using that content as the coffee file.  It errors out not recognizing assertStatus and assert as valid commands, both are not defined.

The example in the readme has the {test} and code but I haven't seen any good examples of incorporating all of the pieces together.  So I'm a tad lost on what's supposed to be there and what all it will really validate.

**Comment by plroebuck** [comment]
I updated my comment with attempt to load ```assert``` from ```chai``` package.

**Comment by plroebuck** [comment]
My ```package.json``` also has the following additions:
```
  "config": {
    "server": {
      "hostname": "localhost",
      "port":     8080
    }
  },
  "scripts": {
    "pretest": "echo Verify server output against RAML...",
    "test": "cd doc && abao api.raml http://$npm_package_config_server_hostname:$npm_package_config_server_port --hookfiles=hooks/*_hooks.js"
  },
  "dependencies": {
    "aboa": "latest",
    "ram2html": "latest",
    ...
  },
  "devDependencies": {
    "chai": "~3.4.1"
  }
```

In my case, the RAML file, ```hooks``` and ```schema``` directories live inside my ```doc``` directory in package root. As such, ```npm test``` will run ```aboa`` for me as a package script.

**Comment by plroebuck** [comment]
@atdiff, is your issue resolved now?

**Comment by atdiff** [comment]
@plroebuck I haven't had a chance to get back to the project to test it out further. I hope to soon and will update then. Thanks!
