### ISSUE TITLE
Throttling requests

### ISSUE THREAD

**Issue by ProLoser** [cybertk/abao#75]
Don't want to DDOS your api, would be nice to introduce some controls and mechanisms around throttling.

**Comment by plroebuck** [comment]
@ProLoser, after further thought, this would seem to be something that goes in *your* server code, not the test tool. Your hooks should deal with "Enhance Your Calm" responses, not **abao** itself. Or am I not understanding your intent here? Kinda doubt that **abao** would trigger this anyway -- no rapid-fire requests done by tool.

**Comment by ProLoser** [comment]
Let's say you parse a raml file with 40 endpoints each with 4 crud methods. A bit of an edge case but not exceptionally unreasonable. This would cause abao to issue 160 requests to the same api in quick succession. I think they would also fire in parallel.

**Comment by galk-in** [comment]
@ProLoser we have mocha under the hood, which run test in series, not parallel. So abao doesn't make DDOS.
