### ISSUE TITLE
Generate skeleton hooks file from CLI

### ISSUE THREAD

**Issue by plroebuck** [cybertk/abao#77]
Add a cmd-line option to generate a file(s) containing skeleton hooks for all routes.

**Comment by galk-in** [comment]
I will do PR for this.

**Comment by galk-in** [comment]
https://github.com/cybertk/abao/pull/91

**Comment by galk-in** [comment]
I want listen ideas about templates and how command should be. Please, lets start discuss.

**Comment by plroebuck** [comment]
I took a glance. Thanks for the kickstart. It's a decent prototype, but there's more to it.
I believe it should:

1) require `chai` assertion module by default so we don't have to explain that it will be required.
2) include 'beforeAll' and 'afterAll' hooks
2) for at least one case, add "commented out" example showing recommended "how to".
3) use template engine instead of hardcoding.
4) error checking. If the file exists already, we should abort. Should `--force` flag override?
5) output format? How should it determine whether to generate CoffeeScript or JavaScript?

Haven't had time to work through these thoughts yet, but weekend is coming.
Sorry for delayed response, and thanks for your effort.

**Comment by plroebuck** [comment]
@ProLoser, have a decent cut of this ready that outputs to stdout, avoiding potential
file overwrite issues. In your opinion, would having a `--template` argument be too advanced?
It would allow more advanced users to create their own `Mustache` template files, while
everyone else gets the JavaScript-based default template I provide.

Any suggestions for the feature, regardless whether you would use it yourself?

**Comment by ProLoser** [comment]
This seems like an interesting/useful idea, but I wouldn't honestly put too much 'configuration' into it. I'd rather just generate a verbose amount of code and let people delete what they want (as long as it's well spaced out).

Again, you may have noted my overall feeling is that I haven't been too pleased with abao's current implementations around testing overall.

**Comment by plroebuck** [comment]
PR #119
