### ISSUE TITLE
GET request has content-length

### ISSUE THREAD

**Issue by raafael911** [cybertk/abao#83]
I encountered the following problem:
We are using a lighttpd server running as a proxy for a fcgi process. It looks like lighttpd does not like GET Requests with a content-length. Every time I run abao with my RAML specifications the GET requests fail with a 400 error code and the following in the lighttpd error log:
GET/HEAD with content-length -> 400

I inspected the packets sent by abao with wireshark and they indeed have an HTTP header field content-length with a value of 2.

**Comment by plroebuck** [comment]
I see the request `Content-Length` header with value of `2` as well with the current version, but haven't checked when it started appearing. You didn't say what version you were using. Find no evidence of an actual request body from quick check though.

**Comment by raafael911** [comment]
Sorry for my missing reply. I was busy the whole weekend. Your fix works for me. Thanks!
