### ISSUE TITLE
Multiple Hook Files

### ISSUE THREAD

**Issue by agrover8** [cybertk/abao#87]
Can we use multiple hook files for single test?

Abao is able to find multiple hook files but running only one hook file.

**Comment by plroebuck** [comment]
Yes (guarded response), if you wanted to organize each endpoint into its own file.
But current codebase does not allow having multiple tests per endpoint (issue #35).

To see your RAML-defined endpoints, run ```abao ``` using the ```--names``` options.

**Comment by agrover8** [comment]
Actually I was trying to run multiple tests per endpoints that's why I tried multiple hook files.

Do you have any idea if anyone is working on issue #35

**Comment by plroebuck** [comment]
I have not yet attempted to extend `lovelyhooks` patch to both *before* **AND** *after* hooks.
It's coming, but picking off low-hanging fruit first...
