### ISSUE TITLE
Add CONTRIBUTING.md

### ISSUE THREAD

**Issue by galk-in** [cybertk/abao#89]
Hello, @plroebuck @cybertk 
I think we should have [CONTRIBUTING.md](https://help.github.com/articles/setting-guidelines-for-repository-contributors/)
Can you write it? or should I make PR with this?

**Comment by plroebuck** [comment]
Meh. Don't care myself. It's kinda obvious. Not interested in notoriety considering my *CoffeeScript* skillz.
