### ISSUE TITLE
Does abao resolve $ref in JSON schema?

### ISSUE THREAD

**Issue by raafael911** [cybertk/abao#92]
Hi and thanks for your great tool. This is actually only a question. I have some JSON schema files which use $ref keywords to reference some object defined in another JSON schema file. (This is important because we have many REST resources which are collections. It is also possible to get each element of a collection by id, so it is convenient to reference them).

So does abao correctly resolve references between JSON schemas as described in the JSON schema specification?

**Comment by duaiwe** [comment]
See #52

**Comment by plroebuck** [comment]
To best of our knowledge, it does.

**Comment by raafael911** [comment]
Actually it does but I had big trouble finding out how it works. You have to use the `--schemas` flag to tell abao which schema files are referenced so it can preload those files. Additionally you have to be careful because the parser abao uses can only handle references where the target schema has an "id" defined.

**Comment by samekmichal** [comment]
So how does one reference an already declared schema as a "type" for a property? Let's say I have this schema declaration.
```
schemas:
  - Link: |
      {
        "$schema": "http://json-schema.org/draft-04/schema#",
        "type": "object",
        "properties": {
          "href": {
            "required": true,
            "type": "string"
          }
        }
      }
```

and I want to reference the above in another schema. Is the following the way to do it?
```
...
  - Meta: |
      {
        "$schema": "http://json-schema.org/draft-04/schema#",
        "type": "object",
        "properties": {
          "self": {
            "$ref": "Link"
          }
        }
      }
```

Any help on this is greatly appreciated!

**Comment by raafael911** [comment]
Here is an example how I managed to do it:

In schema file user.json:
```
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "id": "file://schemas/REST-Alarm-API/user#",
  "definitions": {
    "user" : {
        "description": "",
        "type": "object",
        "properties": {
            "name": { "type": "integer" }
         }
    }
  },
  "title": "User",
  "description": "User definition",
  "type": "object",
  "properties": {
    "user": {
      "$ref": "#/definitions/useruser"
    }
  }
}
```

In schema file users.json:
```
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "title": "Users",
    "description": "Array of Users",
    "type": "object",
    "properties": {
        "users" : {
            "description": "Array of Users",
            "type": "array",
            "items": {
                "$ref": "file://path/on/your/machine/user#/definitions/user"
            }
        }
    }
}
```

In this example you see two possibilities to reference schemas. In user.json I defined how a user object looks like under the `definitions` property. In users.json I reference this definition in another file. Important for resolving the reference is the ´id´property in user.json.

**Comment by samekmichal** [comment]
Thank you! `id` did the trick!
