### ISSUE TITLE
Clean up stale branches

### ISSUE THREAD

**Issue by plroebuck** [cybertk/abao#99]
Are any of the following branches still of value?
* ci-npm
* lint
* bug/24
* deps

If not, let's delete them. Otherwise, do merges necessary to bring them back up-to-date.

**Comment by cybertk** [comment]
Updated

- ci-npm was removed
- lint was opened as PR #102
- bug/24 was remove
- deps was opened as PR #101

**Comment by galk-in** [comment]
Update

- Lint Done. Please check and say what do you think about max length https://github.com/cybertk/abao/pull/102
- CI in v4 and v5 done. I closed PR #101 and open PR #103. It was faster open new without unsquashed commits. Also see [travis help](https://docs.travis-ci.com/user/languages/javascript-with-nodejs#Node.js-v4-(or-io.js-v3)-compiler-requirements) we need the module for v4 and v5
